swagger: "2.0"
info:
  version: "2016-09-10T07:28:50Z"
  title: "ErrorProcessingService"
host: "qo0rkk2937.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /process:
    post:
      x-amazon-apigateway-auth:
        type: aws_iam
      produces:
      - "application/json"
      consumes:
        - application/json
      parameters:
        - name: error 
          in: body
          description: The Error details to process
          schema:
            $ref: '#/definitions/ProcessingError'
      tags:
        - Supplies Store
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:970386504547:function:ErrorHandler/invocations
        httpMethod: POST
        credentials: arn:aws:iam::*:user/*
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "BAD.*":
            statusCode: "400"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "INT.*":
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
      responses:
        200:
          description: Sucess
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/ErrorProcessingResponse'
        400:
          description: Bad request
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'     
            
definitions:

definitions:
  Item:
    properties:
      sku:
        type: "string"
        description: "The unique identifier for the item"
      lineItemDescription:
        type: "string"
        description: "the line item description"
      lineItemType:
        type: "string"
        description: "the line item type"
      supplierName:
        type: "string"
        description: "the supplier of the item"
      quantity:
        type: "integer"
        description: "the quantity of items purchased."
  CreditCardPaymentDetail:
    properties:
      netPaymentAmount:
        type: "number"
        description: "the amount without shipping or tax"
      creditCardProvider:
        type: "string"
        description: "the provider such as mastercard or vis"
      expiryDate:
        type: "string"
        description: "cc expiry date"
      verificationCode:
        type: "string"
        description: "the cc verificatio code"
  Error:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  Items:
    type: "array"
    items:
      $ref: "#/definitions/Item"
  Order:
    properties:
      username:
        type: "string"
        description: "unique identifier for the user"
      Items:
        description: "List of items in the order."
        $ref: "#/definitions/Items"
      CreditCardPaymentDetail:
        description: "payment details for the order"
        $ref: "#/definitions/CreditCardPaymentDetail"
      
  ProcessingError:
    properties:
      Order:
        type: object
        description: the order in error, potentially modified
        $ref: "#/definitions/Order"
      serviceId:
        type: string
        description: the service reporting the error 
      messageDetail:
        type: string
        description: a descripton of the error or exception 

  ErrorProcessingResponse:
    properties:
      status:
        type: string
        description: The status of the error being reported - either COMPLETE or EXCEPTION
      errorId: 
        type: string 
        description: the errorId of a related error that was thrown by trying to log this processing error. 
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
