swagger: "2.0"
info:
  version: "2016-09-10T07:28:50Z"
  title: "OrderService"
host: "qo0rkk2937.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /orders:
    post:
      x-amazon-apigateway-auth:
        type: none
      produces:
      - "application/json"
      consumes:
        - application/json
      parameters:
        - name: NewOrder
          in: body
          description: New Order details.
          schema:
            $ref: '#/definitions/NewOrder'
      tags:
        - Supplies Store
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:970386504547:function:OrderCaptureHandler/invocations
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "poc.sa.ms.control.order.OrderCaptureHandler",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "BAD.*":
            statusCode: "400"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
          "INT.*":
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/NewOrderResponse'
        400:
          description: Bad request
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: '#/definitions/Error'  
            
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 500
            }
        responses:
          "default":
            statusCode: "500"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        500:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"   
definitions:
  Item:
    properties:
      sku:
        type: "string"
        description: "The unique identifier for the item"
      lineItemDescription:
        type: "string"
        description: "the line item description"
      lineItemType:
        type: "string"
        description: "the line item type"
      supplierName:
        type: "string"
        description: "the supplier of the item"
      quantity:
        type: "integer"
        description: "the quantity of items purchased."
  CreditCardPaymentDetail:
    properties:
      netPaymentAmount:
        type: "number"
        description: "the amount without shipping or tax"
      creditCardProvider:
        type: "string"
        description: "the provider such as mastercard or vis"
      expiryDate:
        type: "string"
        description: "cc expiry date"
      verificationCode:
        type: "string"
        description: "the cc verificatio code"
  Error:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  Items:
    type: "array"
    items:
      $ref: "#/definitions/Item"
  NewOrder:
    properties:
      username:
        type: "string"
        description: "unique identifier for the user"
      Items:
        description: "List of items in the order."
        $ref: "#/definitions/Items"
      CreditCardPaymentDetail:
        description: "payment details for the order"
        $ref: "#/definitions/CreditCardPaymentDetail"
  NewOrderResponse:
    properties:
      orderId:
        type: "string"
        description: "The generated unique identifier for the new order"
