package poc.sa.ms.model.order;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import poc.sa.ms.daoconfig.DdbConfiguration;

@DynamoDBTable(tableName = DdbConfiguration.ORDER_TABLE_NAME)
public class PersistedOrder {
  
  public PersistedOrder(String orderPayload) {
    this.orderPayload = orderPayload;
  }
  
  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "orderId")
  private String orderId;
  
  @DynamoDBAttribute(attributeName = "orderPayload")
  private String orderPayload;
  
  @DynamoDBAutoGeneratedKey
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getOrderPayload() {
    return orderPayload;
  }

  public void setOrderPayload(String orderPayload) {
    this.orderPayload = orderPayload;
  }
  
  

}
