package poc.sa.ms.dao.order;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import poc.sa.ms.common.model.config.DdbConfiguration;

@DynamoDBTable(tableName = DdbConfiguration.ORDER_TABLE_NAME)
public class PersistedOrder {
  
  public PersistedOrder(String orderPayload) {
    this.orderPayload = orderPayload;
  }
  
  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "orderId")
  private String orderId;
  
  @DynamoDBAttribute(attributeName = "orderPayload")
  private String orderPayload;
  
  @DynamoDBAttribute(attributeName = "orderStatus")
  private String status;
  
  @DynamoDBAutoGeneratedKey
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getOrderPayload() {
    return orderPayload;
  }

  public void setOrderPayload(String orderPayload) {
    this.orderPayload = orderPayload;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
    result = prime * result + ((orderPayload == null) ? 0 : orderPayload.hashCode());
    result = prime * result + ((status == null) ? 0 : status.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    PersistedOrder other = (PersistedOrder) obj;
    if (orderId == null) {
      if (other.orderId != null)
        return false;
    } else if (!orderId.equals(other.orderId))
      return false;
    if (orderPayload == null) {
      if (other.orderPayload != null)
        return false;
    } else if (!orderPayload.equals(other.orderPayload))
      return false;
    if (status == null) {
      if (other.status != null)
        return false;
    } else if (!status.equals(other.status))
      return false;
    return true;
  }

  @Override
  public String toString() {
    return "PersistedOrder [orderId=" + orderId + ", orderPayload=" + orderPayload + ", status=" + status + "]";
  }

}
