package poc.sa.ms.model.error;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import poc.sa.ms.daoconfig.DdbConfiguration;

@DynamoDBTable(tableName = DdbConfiguration.ERROR_TABLE_NAME)
public class ErrorWrapper {
  
  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "errorId")
  private String errorId;
  @DynamoDBAttribute(attributeName = "orderPayload")
  private String order;
  @DynamoDBAttribute(attributeName = "serviceId")
  private String serviceId;
  @DynamoDBAttribute(attributeName = "messageDetail")
  private String messageDetail;
  
  public String getErrorId() {
    return errorId;
  }
  public void setErrorId(String errorId) {
    this.errorId = errorId;
  }
  public String getOrder() {
    return order;
  }
  /*
   * json representation of the order string.
   */
  public void setOrder(String order) {
    this.order = order;
  }
  public String getServiceId() {
    return serviceId;
  }
  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }
  public String getMessageDetail() {
    return messageDetail;
  }
  public void setMessageDetail(String messageDetail) {
    this.messageDetail = messageDetail;
  }
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((errorId == null) ? 0 : errorId.hashCode());
    result = prime * result + ((messageDetail == null) ? 0 : messageDetail.hashCode());
    result = prime * result + ((order == null) ? 0 : order.hashCode());
    result = prime * result + ((serviceId == null) ? 0 : serviceId.hashCode());
    return result;
  }
  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    ErrorWrapper other = (ErrorWrapper) obj;
    if (errorId == null) {
      if (other.errorId != null)
        return false;
    } else if (!errorId.equals(other.errorId))
      return false;
    if (messageDetail == null) {
      if (other.messageDetail != null)
        return false;
    } else if (!messageDetail.equals(other.messageDetail))
      return false;
    if (order == null) {
      if (other.order != null)
        return false;
    } else if (!order.equals(other.order))
      return false;
    if (serviceId == null) {
      if (other.serviceId != null)
        return false;
    } else if (!serviceId.equals(other.serviceId))
      return false;
    return true;
  }
  @Override
  public String toString() {
    return "ErrorWrapper [errorId=" + errorId + ", order=" + order + ", serviceId=" + serviceId + ", messageDetail="
        + messageDetail + "]";
  }
  
  

}
